import { Metadata } from "next";


export const metadata: Metadata = {
  title: "Me - About",
  description: "Generated by create next app",
};

const AboutLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <div>
      <header>
        <h1>About Us</h1>
      </header>
      <main>{children}</main>
      <footer>
        <p>&copy; 2023 Your Company</p>
      </footer>
    </div>
  );
};

export default AboutLayout;
