import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import React from "react";
import Link from "next/link";
import Head from "next/head";

import "../styles/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
  metaTitle,
}: {
  children: React.ReactNode;
  metaTitle?: string;
}) => {
  return (
    <html lang="en">
      <Head>
        <title>{`Practice - ${metaTitle}`}</title>
        <meta name="description" content="This is a default description" />
      </Head>
      <div
        className={`${geistSans.variable} ${geistMono.variable} flex flex-col min-h-screen`}
      >
        <header className="bg-blue-600 text-white p-4">
          <div className="container mx-auto flex justify-between items-center">
            <h1 className="text-xl font-bold">Practice Pages Router NextJS</h1>
            <ul className="flex space-x-4">
              <li>
                <Link href="/pages-router/">Home</Link>
              </li>
              <li>
                <Link href="/pages-router/about">About</Link>
              </li>
            </ul>
          </div>
        </header>
        <main className="container flex-1 mx-auto">{children}</main>
        <footer className="bg-gray-800 text-white p-4 text-center">
          <p>© {new Date().getFullYear()} Mesanfaz</p>
        </footer>
      </div>
    </html>
  );
};

export default RootLayout;
