import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import React from "react";
import Link from "next/link";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Me - Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className={`flex flex-col min-h-screen`}>
          <header className="bg-blue-600 text-white p-4">
            <div className="container mx-auto flex justify-between items-center">
              <h1 className="text-xl font-bold">Practice App Router NextJS</h1>
              <ul className="flex space-x-4">
                <li>
                  <Link href="/">Home</Link>
                </li>
                <li>
                  <Link href="/about">About</Link>
                </li>
              </ul>
            </div>
          </header>
          <main className="container flex-1 mx-auto">{children}</main>
          <footer className="bg-gray-800 text-white p-4 text-center">
            <p>© {new Date().getFullYear()} mesanfaz</p>
          </footer>
        </div>
      </body>
    </html>
  );
}
